version: '3.8'

services:
  postgres:
    container_name: mypostgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    networks:
      - pg_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
    ports:
      - "5050:80"
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
    driver: bridge
